import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Box, Typography } from "@mui/material"
import { Collection } from '@/components'
import { useAccount } from 'wagmi'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { isConnected } = useAccount()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{height: '100px'}} />
        {!isConnected && <Box sx={{ height: '80vh', width: '100vw', display: 'grid', placeItems: 'center' }}>
          <Typography variant="h2" component="h1" color="white" gutterBottom>
            Connect Wallet to view your NFTs
          </Typography>
        </Box>}
        <Collection/>
      </main>
    </>
  )
}


