import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Minter } from '@/components'
import { useAccount } from 'wagmi'
import { Box, Typography } from "@mui/material"

const inter = Inter({ subsets: ['latin'] })

export default function MintPage() {

  const { isConnected } = useAccount()

  if (!isConnected) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Box sx={{ height: '100px' }} />
          {!isConnected && <Box sx={{ height: '80vh', width: '100vw', display: 'grid', placeItems: 'center' }}>
            <Typography variant="h2" component="h1" color="white" gutterBottom>
              Connect Wallet to Mint NFTs
            </Typography>
          </Box>}
        </main>
      </>
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ height: '100px' }} />
        <Minter />
      </main>
    </>
  )
}
